language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

stages:
  - lint
  - test
  - build
  - docs deploy
  - npm deploy

branches:
  only:
    - develop
    - release/*
    - master

cache: npm

install:
  - npm install
  - npm run bootstrap

script:

jobs:
  include:
    - stage: lint
      script: npm run lint

    - stage: test
      script: npm run test:ci

    - stage: build
      script: npm run build:prod

    - stage: docs deploy
      if: branch = master
      script: npm run docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/.vuepress/dist
        target_branch: gh-pages

    - stage: npm deploy
      if: branch = master
      script: echo "Deploying to npm"
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: npm run publish:ci
        skip_cleanup: true
        on:
          branch: master
          tags: true

notifications:
  email: false
