export enum TransactionType {
  CoinBase = 1,
  Transfer = 2,
  AccountAlias = 3,
  NodeRegister = 4,
  NodeDeposit = 5,
  NodeDepositCancel = 6,
  YellowPunish = 7,
  RedPunish = 8,
  NodeStop = 9,
  CrossChain = 10,
  ChainRegister = 11,
  ChainDestroy = 12,
  ChainAssetAdd = 13,
  ChainAssetRemove = 14,
  ContractCreate = 15,
  ContractCall = 16,
  ContractDelete = 17,
  ContractTransfer = 18,
  ContractGasRefund = 19,
  ContractNodeRegister = 20,
  ContractNodeDeposit = 21,
  ContractNodeDepositCancel = 22,
  ContractNodeStop = 23,
  VerifierChange = 24,
}
