export enum TransactionType {
  CoinBase = 1,
  Transfer = 2,
  AccountAlias = 3,
  AgentRegister = 4,
  AgentDeposit = 5,
  AgentDepositCancel = 6,
  YellowPunish = 7,
  RedPunish = 8,
  AgentStop = 9,
  CrossChain = 10,
  ChainRegister = 11,
  ChainDestroy = 12,
  ChainAssetAdd = 13,
  ChainAssetRemove = 14,
  ContractCreate = 15,
  ContractCall = 16,
  ContractDelete = 17,
  ContractTransfer = 18,
  ContractGasRefund = 19,
  ContractAgentRegister = 20,
  ContractAgentDeposit = 21,
  ContractAgentDepositCancel = 22,
  ContractAgentStop = 23,
  VerifierChange = 24,
}
